new configure option --enable-gmplink to install symlinks of gmp->mpir

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -866,6 +866,8 @@ MAINTAINER_MODE_FALSE
 MAINT
 WANT_MPBSD_TRUE
 WANT_MPBSD_FALSE
+WANT_GMPLINK_TRUE
+WANT_GMPLINK_FALSE
 GMP_NAIL_BITS
 ABI
 HAVE_HOST_CPU_FAMILY_power
@@ -1552,6 +1554,8 @@ Optional Features:
   --enable-cxx            enable C++ support [default=no]
   --enable-fft            enable FFTs for multiplication [default=yes]
   --enable-mpbsd          build Berkeley MP compatibility library
+                          [default=no]
+  --enable-gmplink        create symbolic links named gmp that point to mpir
                           [default=no]
   --enable-nails          use nails on limbs [default=no]
   --enable-profiling      build with profiler support [default=no]
@@ -2787,6 +2791,29 @@ if test "$enable_mpbsd" = "yes"; then
 else
   WANT_MPBSD_TRUE='#'
   WANT_MPBSD_FALSE=
+fi
+
+
+# Check whether --enable-gmplink was given.
+if test "${enable_gmplink+set}" = set; then
+  enableval=$enable_gmplink; case $enableval in
+yes|no) ;;
+*) { { echo "$as_me:$LINENO: error: bad value $enableval for --enable-gmplink, need yes or no" >&5
+echo "$as_me: error: bad value $enableval for --enable-gmplink, need yes or no" >&2;}
+   { (exit 1); exit 1; }; } ;;
+esac
+else
+  enable_gmplink=no
+fi
+
+
+
+if test "$enable_gmplink" = "yes"; then
+  WANT_GMPLINK_TRUE=
+  WANT_GMPLINK_FALSE='#'
+else
+  WANT_GMPLINK_TRUE='#'
+  WANT_GMPLINK_FALSE=
 fi
 
 
@@ -11425,7 +11452,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 11428 "configure"' > conftest.$ac_ext
+  echo '#line 11455 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -13251,11 +13278,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13254: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13281: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13258: \$? = $ac_status" >&5
+   echo "$as_me:13285: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13541,11 +13568,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13544: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13571: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13548: \$? = $ac_status" >&5
+   echo "$as_me:13575: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13645,11 +13672,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13648: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13675: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13652: \$? = $ac_status" >&5
+   echo "$as_me:13679: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15994,7 +16021,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 15997 "configure"
+#line 16024 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16094,7 +16121,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16097 "configure"
+#line 16124 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18514,11 +18541,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18517: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18544: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18521: \$? = $ac_status" >&5
+   echo "$as_me:18548: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18618,11 +18645,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18621: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18648: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18625: \$? = $ac_status" >&5
+   echo "$as_me:18652: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20180,11 +20207,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20183: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20210: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:20187: \$? = $ac_status" >&5
+   echo "$as_me:20214: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20284,11 +20311,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20287: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20314: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:20291: \$? = $ac_status" >&5
+   echo "$as_me:20318: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22471,11 +22498,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22474: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22501: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:22478: \$? = $ac_status" >&5
+   echo "$as_me:22505: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -22761,11 +22788,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22764: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22791: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:22768: \$? = $ac_status" >&5
+   echo "$as_me:22795: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -22865,11 +22892,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22868: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22895: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:22872: \$? = $ac_status" >&5
+   echo "$as_me:22899: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -34254,6 +34281,13 @@ echo "$as_me: error: conditional \"WANT_MPBSD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${WANT_GMPLINK_TRUE}" && test -z "${WANT_GMPLINK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WANT_GMPLINK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WANT_GMPLINK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_YASM_TRUE}" && test -z "${BUILD_YASM_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_YASM\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -34901,6 +34935,8 @@ MAINTAINER_MODE_FALSE!$MAINTAINER_MODE_FALSE$ac_delim
 MAINT!$MAINT$ac_delim
 WANT_MPBSD_TRUE!$WANT_MPBSD_TRUE$ac_delim
 WANT_MPBSD_FALSE!$WANT_MPBSD_FALSE$ac_delim
+WANT_GMPLINK_TRUE!$WANT_GMPLINK_TRUE$ac_delim
+WANT_GMPLINK_FALSE!$WANT_GMPLINK_FALSE$ac_delim
 GMP_NAIL_BITS!$GMP_NAIL_BITS$ac_delim
 ABI!$ABI$ac_delim
 HAVE_HOST_CPU_FAMILY_power!$HAVE_HOST_CPU_FAMILY_power$ac_delim
@@ -34925,8 +34961,6 @@ CC_FOR_BUILD!$CC_FOR_BUILD$ac_delim
 CPP_FOR_BUILD!$CPP_FOR_BUILD$ac_delim
 EXEEXT_FOR_BUILD!$EXEEXT_FOR_BUILD$ac_delim
 U_FOR_BUILD!$U_FOR_BUILD$ac_delim
-LIBM_FOR_BUILD!$LIBM_FOR_BUILD$ac_delim
-CCAS!$CCAS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -34968,6 +35002,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+LIBM_FOR_BUILD!$LIBM_FOR_BUILD$ac_delim
+CCAS!$CCAS$ac_delim
 MPIR_AS!$MPIR_AS$ac_delim
 CXX!$CXX$ac_delim
 CXXFLAGS!$CXXFLAGS$ac_delim
@@ -35024,7 +35060,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 54; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 56; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
